# Generated by Django 3.2.7 on 2021-10-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/default_avatar.png', null=True, upload_to='users/'),
        ),
    ]
