# Generated by Django 3.2.7 on 2021-10-02 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('book_pic', models.ImageField(blank=True, default='book/book_profile.png', null=True, upload_to='books')),
                ('readers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
