# Generated by Django 3.2.7 on 2021-10-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description2',
            field=models.TextField(blank=True),
        ),
    ]
